import { getUserSession } from '@/lib/server/auth';
import { supabaseAdmin } from '@/lib/server/supabase';
import './brand-profile.module.css';

type Profile = { business_summary: string | null; target_audience: string | null; brand_positioning: string | null; tone_of_voice: string | null; brand_values: string[] | null; primary_colour: string | null; secondary_colours: string[] | null; fonts: string[] | null; visual_style: string[] | null; content_guidelines: string[] | null; prohibited_usage: string[] | null; reviewed: boolean };
const list = (value: string[] | null | undefined) => value?.filter(Boolean) || [];
const safeColour = (value: string | null) => value && /^#[0-9a-f]{3,8}$/i.test(value) ? value : null;
function List({ items, empty }: { items: string[]; empty: string }) { return items.length ? <ul className="brand-list">{items.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="brand-muted">{empty}</p>; }

export default async function BrandProfilePage() {
  const session = await getUserSession();
  if (!session?.userId) return null;
  const db = supabaseAdmin();
  const { data: client } = await db.from('clients').select('id,business_name,business_type,location').eq('owner_user_id', session.userId).maybeSingle();
  const { data: profile } = client ? await db.from('brand_profiles').select('business_summary,target_audience,brand_positioning,tone_of_voice,brand_values,primary_colour,secondary_colours,fonts,visual_style,content_guidelines,prohibited_usage,reviewed').eq('client_id', client.id).maybeSingle() : { data: null };
  const brand = profile as Profile | null;
  if (!client || !brand?.reviewed) return <><p className="app-eyebrow">Brand book</p><h1>Build your brand book first.</h1><section className="notice"><b>Nothing is assumed</b><p>Start with your public website, review the draft, and approve it before Outreach+ uses it in campaigns or conversations.</p></section><a className="dash-primary" href="/onboarding">Create my brand book</a></>;

  const primary = safeColour(brand.primary_colour);
  const colours = [primary, ...list(brand.secondary_colours).map(safeColour).filter((value): value is string => Boolean(value))].filter((value): value is string => Boolean(value));
  const fonts = list(brand.fonts);
  return <article className="brand-book"><header className="brand-book-cover"><p className="app-eyebrow">Approved brand book</p><p className="brand-book-made">Built with Outreach+</p><h1>{client.business_name}</h1><p>{client.business_type} · {client.location}</p><span>Used to guide every approved Outreach+ campaign.</span></header><section className="brand-book-section"><p className="brand-section-number">01 · Brand overview</p><div><h2>What the brand stands for.</h2><p className="brand-lede">{brand.business_summary || `${client.business_name} is a ${client.business_type} in ${client.location}.`}</p><div className="brand-quote">{brand.brand_positioning || 'A clear, owner-approved brand direction will guide every campaign.'}</div></div></section><section className="brand-book-section brand-book-split"><div><p className="brand-section-number">02 · Typography</p><h2>How the brand speaks.</h2><div className="type-samples">{fonts.length ? fonts.map((font, index) => <div key={font}><small>{index === 0 ? 'PRIMARY TYPEFACE' : 'SUPPORTING TYPEFACE'}</small><strong style={{ fontFamily: font }}>{font}</strong><span style={{ fontFamily: font }}>Aa Bb Cc 0123</span></div>) : <p className="brand-muted">Typography can be added when the client confirms it.</p>}</div></div><div><p className="brand-section-number">03 · Colour palette</p><h2>Recognisable at a glance.</h2><div className="colour-swatches">{colours.length ? colours.map((colour, index) => <div key={`${colour}-${index}`}><i style={{ backgroundColor: colour }} /><strong>{index === 0 ? 'Primary' : 'Accent'}</strong><span>{colour.toUpperCase()}</span></div>) : <p className="brand-muted">No colours were confirmed from the website.</p>}</div></div></section><section className="brand-book-section brand-book-split"><div><p className="brand-section-number">04 · Brand voice</p><h2>What every message should feel like.</h2><div className="brand-voice"><strong>{brand.tone_of_voice || 'To be confirmed'}</strong><List items={list(brand.brand_values)} empty="Brand values will appear here after the client confirms them." /></div></div><div><p className="brand-section-number">05 · Campaign guardrails</p><h2>Consistency, without guesswork.</h2><div className="brand-rules"><div><small>CONTENT DIRECTION</small><List items={list(brand.content_guidelines).length ? list(brand.content_guidelines) : list(brand.visual_style)} empty="Outreach+ will use the approved tone and business context." /></div><div><small>PROTECT THE BRAND</small><List items={list(brand.prohibited_usage)} empty="Outreach+ will never invent offers, prices, dates or menu items." /></div></div></div></section><footer className="brand-book-footer"><div><b>Ready for campaign work</b><p>Outreach+ applies this approved brand book to campaign plans, captions and recommendations.</p></div><a className="dash-primary" href="/dashboard/create-campaign">Create a campaign</a></footer></article>;
}
